version: '3.8'

services:
  web:
    build: .
    container_name: thz_database_gunicorn
    command: gunicorn --bind 0.0.0.0:8001 thz_database.wsgi:application
    volumes:
      - .:/app # For development code changes
      - static_volume:/app/staticfiles # Django collects static files here
      - media_volume:/app/media        # For media files
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
    # depends_on:
    #   - db

  nginx:
    image: nginx:latest
    container_name: thz_database_nginx
    ports:
      - "6080:80"
      - "6443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - static_volume:/app/staticfiles # Nginx serves static files from here
      - media_volume:/app/media        # Nginx serves media files from here
    depends_on:
      - web

volumes:
  static_volume: # Define the named volume for collected static files
  media_volume:  # Define the named volume for media files