# Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install system dependencies (if any)
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     # Example: libpq-dev gcc \
#     && rm -rf /var/lib/apt/lists/*
RUN apt-get install libhdf5-dev

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app/

# Expose the port Gunicorn will run on (can still be 8000 internally)
EXPOSE 8000

# Define the command to run your application using Gunicorn
# Replace 'myproject.wsgi' with 'your_project_name.wsgi'
# The number of workers can be adjusted based on your server's resources
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]